# Etapa 1: Build
FROM node:18 AS build
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN npm prune --production

# Etapa 2: Produção
FROM node:18-alpine3.21
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

EXPOSE 3000
#CMD ["npm", "run", "start"]
CMD ["node", "dist/main.js"]
