name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # Essencial para OIDC
  contents: read

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::231224359494:role/ecr-role  # Substitua SEU_AWS_ACCOUNT_ID pelo seu número real
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Seus passos de build e push de imagem Docker podem vir aqui

      - name: Build ECR image
        env: 
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
        run: |
          docker build -t $REGISTRY/rocketseat-ci:f1c93d3 -f DevOps-main/api/Dockerfile DevOps-main/api/
          docker push -t 231224359494.dkr.ecr.us-east-1.amazonaws.com/rocketseat-ci:${{steps.generate_tag.outputs.sha}}