name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Aumentei o array para incluir 16, 18, 20 como na sua imagem
        # Se você quiser 24, pode voltar a incluir
        node: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup node | ${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          # Cache alterado para 'yarn' como na sua imagem, se for o caso
          cache: "npm"

      # Se ele não fazia parte do seu código original ou não for necessário, pode remover
      - run: npm install

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7) 
          echo "sha=$SHA" >> $GITHUB_OUTPUT
        shell: bash # CORREÇÃO 2: Adicionado para garantir que o bash seja usado

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: echo "franciscodouglas" ${{secrets.DOCKERHUB_USERNAME}}
          password: echo "${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        # Certifique-se de que o caminho '-f DevOps-main/api/dockerfile DevOps-main/api' esteja correto
        run: docker build -t franciscodouglas/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}} -f DevOps-main/api/dockerfile DevOps-main/api

      - name: Push image
        run: docker push franciscodouglas/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}}
